### ISSUE TITLE
Show failure if binary of another platform has been specified

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-automation#140]
As of now you will get the following output when you are using a binary of a different platform, e.g you are on linux but want to use a DMG image for OS X:

> 00:00:27.038 *** Installing build: /mozilla/code/mozmill-ci/jenkins-master/jobs/ondemand_update/workspace/builds/firefox-27.0.en-US.mac.dmg
00:00:27.038 Traceback (most recent call last):
00:00:27.038   File "/mozilla/code/mozmill-ci/jenkins-master/jobs/ondemand_update/workspace/mozmill-env-mac/bin/testrun_update", line 8, in <module>
00:00:27.039     load_entry_point('mozmill-automation==2.0.6.1', 'console_scripts', 'testrun_update')()
00:00:27.039   File "/mozilla/code/mozmill-ci/jenkins-master/jobs/ondemand_update/workspace/mozmill-env-mac/python-lib/mozmill_automation/testrun.py", line 797, in update_cli
00:00:27.041     exec_testrun(UpdateTestRun)
00:00:27.041   File "/mozilla/code/mozmill-ci/jenkins-master/jobs/ondemand_update/workspace/mozmill-env-mac/python-lib/mozmill_automation/testrun.py", line 769, in exec_testrun
00:00:27.042     cls().run()
00:00:27.042   File "/mozilla/code/mozmill-ci/jenkins-master/jobs/ondemand_update/workspace/mozmill-env-mac/python-lib/mozmill_automation/testrun.py", line 359, in run
00:00:27.042     print "*** Uninstalling build: %s" % self._folder
00:00:27.042 AttributeError: 'UpdateTestRun' object has no attribute '_folder'

It would be better to throw an appropriate failure in case of such a condition with a clear message what's wrong.

**Comment by whimboo** [comment]
We are going to discontinue Mozmill in favor of [Firefox UI Tests](https://github.com/mozilla/firefox-ui-tests). So I'm going to wont fix this PR.
