### ISSUE TITLE
Execution of testruns broken for Mozmill 2.1 (master branch)

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-automation#201]
Currently we fail to execute the testrun scripts on the master branch. The exception I see is the following: 

root ERROR | Execution of test-run aborted
Traceback (most recent call last):
  File "/mozilla/code/mozmill-automation/mozmill_automation/testrun.py", line 736, in run_update_tests
    TestRun.run_tests(self)
  File "/mozilla/code/mozmill-automation/mozmill_automation/testrun.py", line 302, in run_tests
    self._mozmill = mozmill.MozMill.create(**mozmill_args)
  File "/mozilla/code/mozmill/mozmill/mozmill/__init__.py", line 166, in create
    runner = runner_class(binary=binary, profile=profile, **runner_args)
TypeError: FirefoxRunner() got multiple values for keyword argument 'binary'
root INFO  | Removing test repository: /tmp/tmpP6xq9r.workspace/mozmill-tests
Traceback (most recent call last):
  File "/mozilla/code/mozmill-automation/mozmill_automation/testrun.py", line 359, in run
    self.run_tests()
  File "/mozilla/code/mozmill-automation/mozmill_automation/testrun.py", line 713, in run_tests
    self.run_update_tests(False)
  File "/mozilla/code/mozmill-automation/mozmill_automation/testrun.py", line 740, in run_update_tests
    update_data = self._mozmill.persisted[self.type]
AttributeError: 'UpdateTestRun' object has no attribute '_mozmill'

It's most likely a regression from the dependency bump of mozbase packages as done on [bug 1111682](https://bugzilla.mozilla.org/show_bug.cgi?id=1111682).

**Comment by whimboo** [comment]
PR #202 has been merged.
